# Generated by Django 5.0.4 on 2024-05-02 20:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('first_name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(6)])),
                ('account_level', models.TextField(choices=[('0', 'Admin'), ('1', 'Staff'), ('2', 'Student')], default='2', max_length=7)),
                ('person_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_num', models.BigAutoField(primary_key=True, serialize=False)),
                ('equipment_approvel_status', models.CharField(choices=[('0', 'Denied'), ('1', 'Pending'), ('2', 'Approved')], default='1', max_length=8)),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('usage_date', models.TextField(null=True)),
                ('return_date', models.DateField()),
                ('delivered_date', models.DateField()),
                ('overdue', models.BooleanField(default=False)),
                ('note', models.CharField(max_length=255)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.admin')),
            ],
        ),
        migrations.AddField(
            model_name='admin',
            name='list_of_booking',
            field=models.ManyToManyField(to='inventory.booking'),
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('equip_name', models.CharField(max_length=32)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('equip_type', models.CharField(max_length=32)),
                ('on_site', models.BooleanField()),
                ('borrowable', models.BooleanField()),
                ('warranty', models.DateField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('past_booking_nums', models.ManyToManyField(to='inventory.booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='equipment_list',
            field=models.ManyToManyField(to='inventory.equipment'),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('audit_date', models.DateField()),
                ('location', models.TextField(max_length=200)),
                ('status', models.CharField(choices=[('0', 'Denied'), ('1', 'Pending'), ('2', 'Approved')], default='1', max_length=8)),
                ('comments', models.TextField(max_length=255)),
                ('history', models.TextField(max_length=255)),
                ('equipment_list', models.ManyToManyField(to='inventory.equipment')),
            ],
        ),
        migrations.AddField(
            model_name='admin',
            name='person_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.person'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_num', models.BigAutoField(primary_key=True, serialize=False)),
                ('report_type', models.TextField(max_length=255)),
                ('generation_date', models.DateField(auto_now_add=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.admin')),
                ('inventory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_status', models.CharField(choices=[('0', 'Denied'), ('1', 'Pending'), ('2', 'Approved')], default='1', max_length=8)),
                ('person_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.person')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.user'),
        ),
    ]
